In [50]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/insurance/insurance.csv


In [51]:
import numpy as np
import matplotlib.pyplot as mlt
import pandas as pd

In [52]:
dataset = pd.read_csv('../input/insurance/insurance.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [53]:
print(X)

[[19 'female' 27.9 0 'yes' 'southwest']
 [18 'male' 33.77 1 'no' 'southeast']
 [28 'male' 33.0 3 'no' 'southeast']
 ...
 [18 'female' 36.85 0 'no' 'southeast']
 [21 'female' 25.8 0 'no' 'southwest']
 [61 'female' 29.07 0 'yes' 'northwest']]


In [54]:
print(y)

[16884.92  1725.55  4449.46 ...  1629.83  2007.94 29141.36]


In [55]:
from sklearn.preprocessing import LabelEncoder
le_gender = LabelEncoder()
X[:, 1] = le_gender.fit_transform(X[:, 1])
le_smoke = LabelEncoder()
X[:, 4] = le_smoke.fit_transform(X[:, 4])

In [56]:
print(X)

[[19 0 27.9 0 1 'southwest']
 [18 1 33.77 1 0 'southeast']
 [28 1 33.0 3 0 'southeast']
 ...
 [18 0 36.85 0 0 'southeast']
 [21 0 25.8 0 0 'southwest']
 [61 0 29.07 0 1 'northwest']]


In [57]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [-1])], remainder = 'passthrough')
X = ct.fit_transform(X)

In [58]:
print(X)

[[0.0 0.0 0.0 ... 27.9 0 1]
 [0.0 0.0 1.0 ... 33.77 1 0]
 [0.0 0.0 1.0 ... 33.0 3 0]
 ...
 [0.0 0.0 1.0 ... 36.85 0 0]
 [0.0 0.0 0.0 ... 25.8 0 0]
 [0.0 1.0 0.0 ... 29.07 0 1]]


In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [60]:
print(X_train)

[[0.0 0.0 0.0 ... 34.1 4 1]
 [0.0 0.0 1.0 ... 34.43 0 0]
 [1.0 0.0 0.0 ... 36.67 2 1]
 ...
 [0.0 0.0 1.0 ... 25.08 0 0]
 [0.0 1.0 0.0 ... 35.53 0 0]
 [0.0 0.0 0.0 ... 18.5 1 0]]


In [61]:
print(X_test)

[[0.0 0.0 0.0 ... 30.2 1 0]
 [0.0 0.0 1.0 ... 29.37 1 0]
 [0.0 1.0 0.0 ... 40.565 2 1]
 ...
 [1.0 0.0 0.0 ... 40.28 0 0]
 [0.0 0.0 1.0 ... 39.05 3 1]
 [1.0 0.0 0.0 ... 24.795 3 0]]


In [62]:
print(y_train)

[40182.25  1137.47 38511.63 ...  5415.66  1646.43  4766.02]


In [76]:
print(y_test)

[ 9724.53  8547.69 45702.02 12950.07  9644.25  4500.34  2198.19 11436.74
  7537.16  5425.02  6753.04 10493.95  7337.75  4185.1  18310.74 10702.64
 12523.6   3490.55  6457.84 33475.82 23967.38 12643.38 23045.57 23065.42
  1674.63  4667.61  3732.63  7682.67  3756.62  8413.46  8059.68 48970.25
 12979.36 20630.28 14571.89  4137.52  8347.16 51194.56 40003.33  1880.49
  5458.05  2867.12 20149.32 47496.49 36149.48 26018.95 19749.38  6940.91
  4718.2  22192.44  2899.49 18838.7  23568.27 46255.11 24227.34  3268.85
  2322.62  8827.21 14478.33 13112.6   1253.94 46718.16 13919.82  9630.4
 10736.87  9880.07 32548.34 38746.36  3180.51  8162.72 13041.92 11554.22
 16232.85 13887.97 13012.21 13217.09  7147.1   7731.43 20296.86 47403.88
 11658.38 45863.21  2055.32  7441.05 41034.22 18972.49  3410.32  2699.57
 12333.83 36837.47  6334.34 10214.64 17878.9   8515.76  4518.83  5148.55
 42303.69 38998.55  5327.4  10602.39  1824.29  5377.46  4349.46 37742.58
 32787.46  3353.47 10577.09  3556.92 11944.59 52590.

In [64]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [77]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1.12e+04 9.72e+03]
 [9.49e+03 8.55e+03]
 [3.82e+04 4.57e+04]
 [1.63e+04 1.30e+04]
 [6.91e+03 9.64e+03]
 [3.96e+03 4.50e+03]
 [1.58e+03 2.20e+03]
 [1.44e+04 1.14e+04]
 [9.01e+03 7.54e+03]
 [7.51e+03 5.43e+03]
 [4.49e+03 6.75e+03]
 [1.03e+04 1.05e+04]
 [8.80e+03 7.34e+03]
 [3.80e+03 4.19e+03]
 [2.79e+04 1.83e+04]
 [1.07e+04 1.07e+04]
 [1.13e+04 1.25e+04]
 [6.11e+03 3.49e+03]
 [8.24e+03 6.46e+03]
 [2.71e+04 3.35e+04]
 [3.36e+04 2.40e+04]
 [1.44e+04 1.26e+04]
 [1.17e+04 2.30e+04]
 [3.21e+04 2.31e+04]
 [4.17e+03 1.67e+03]
 [9.25e+03 4.67e+03]
 [1.08e+03 3.73e+03]
 [9.80e+03 7.68e+03]
 [3.77e+03 3.76e+03]
 [1.04e+04 8.41e+03]
 [9.01e+03 8.06e+03]
 [4.01e+04 4.90e+04]
 [1.57e+04 1.30e+04]
 [1.39e+04 2.06e+04]
 [2.48e+04 1.46e+04]
 [5.17e+03 4.14e+03]
 [1.26e+04 8.35e+03]
 [3.08e+04 5.12e+04]
 [3.35e+04 4.00e+04]
 [3.67e+03 1.88e+03]
 [3.98e+03 5.46e+03]
 [3.99e+03 2.87e+03]
 [3.05e+04 2.01e+04]
 [3.95e+04 4.75e+04]
 [2.78e+04 3.61e+04]
 [5.09e+03 2.60e+04]
 [1.06e+04 1.97e+04]
 [7.83e+03 6.